// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using WebAPI.Data;

namespace WebAPI.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("WebAPI.Data.Models.Prefix", b =>
                {
                    b.Property<int>("PrefixID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .HasMaxLength(20);

                    b.HasKey("PrefixID");

                    b.ToTable("Prefixes");
                });

            modelBuilder.Entity("WebAPI.Data.Models.Suffix", b =>
                {
                    b.Property<int>("SuffixID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.HasKey("SuffixID");

                    b.ToTable("Suffixes");
                });

            modelBuilder.Entity("WebAPI.Data.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<string>("FirstName")
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .HasMaxLength(50);

                    b.Property<string>("MiddleName");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUsername");

                    b.Property<string>("PasswordHash");

                    b.Property<int?>("PrefixID");

                    b.Property<int?>("SuffixID");

                    b.Property<DateTime?>("UpdatedOn");

                    b.Property<string>("Username");

                    b.HasKey("UserID");

                    b.HasIndex("PrefixID");

                    b.HasIndex("SuffixID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebAPI.Data.Models.User", b =>
                {
                    b.HasOne("WebAPI.Data.Models.Prefix", "Prefix")
                        .WithMany()
                        .HasForeignKey("PrefixID");

                    b.HasOne("WebAPI.Data.Models.Suffix", "Suffix")
                        .WithMany()
                        .HasForeignKey("SuffixID");
                });
#pragma warning restore 612, 618
        }
    }
}
